export const id52772 = {
  "meals": [
  {
  "idMeal": "52772",
  "strMeal": "Teriyaki Chicken Casserole",
  "strDrinkAlternate": null,
  "strCategory": "Chicken",
  "strArea": "Japanese",
  "strInstructions": "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
  "strTags": "Meat,Casserole",
  "strYoutube": "https://www.youtube.com/watch?v=4aZr5hZXP_s",
  "strIngredient1": "soy sauce",
  "strIngredient2": "water",
  "strIngredient3": "brown sugar",
  "strIngredient4": "ground ginger",
  "strIngredient5": "minced garlic",
  "strIngredient6": "cornstarch",
  "strIngredient7": "chicken breasts",
  "strIngredient8": "stir-fry vegetables",
  "strIngredient9": "brown rice",
  "strIngredient10": "",
  "strIngredient11": "",
  "strIngredient12": "",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": null,
  "strIngredient17": null,
  "strIngredient18": null,
  "strIngredient19": null,
  "strIngredient20": null,
  "strMeasure1": "3/4 cup",
  "strMeasure2": "1/2 cup",
  "strMeasure3": "1/4 cup",
  "strMeasure4": "1/2 teaspoon",
  "strMeasure5": "1/2 teaspoon",
  "strMeasure6": "4 Tablespoons",
  "strMeasure7": "2",
  "strMeasure8": "1 (12 oz.)",
  "strMeasure9": "3 cups",
  "strMeasure10": "",
  "strMeasure11": "",
  "strMeasure12": "",
  "strMeasure13": "",
  "strMeasure14": "",
  "strMeasure15": "",
  "strMeasure16": null,
  "strMeasure17": null,
  "strMeasure18": null,
  "strMeasure19": null,
  "strMeasure20": null,
  "strSource": null,
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
  }
  ]
  };

export const id11007 = {
  "drinks": [
  {
  "idDrink": "11007",
  "strDrink": "Margarita",
  "strDrinkAlternate": null,
  "strTags": "IBA,ContemporaryClassic",
  "strVideo": null,
  "strCategory": "Ordinary Drink",
  "strIBA": "Contemporary Classics",
  "strAlcoholic": "Alcoholic",
  "strGlass": "Cocktail glass",
  "strInstructions": "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
  "strInstructionsES": null,
  "strInstructionsDE": "Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Strofina il bordo del bicchiere con la fetta di lime per far aderire il sale.\r\nAvere cura di inumidire solo il bordo esterno e cospargere di sale.\r\nIl sale dovrebbe presentarsi alle labbra del bevitore e non mescolarsi mai al cocktail.\r\nShakerare gli altri ingredienti con ghiaccio, quindi versarli delicatamente nel bicchiere.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg",
  "strIngredient1": "Tequila",
  "strIngredient2": "Triple sec",
  "strIngredient3": "Lime juice",
  "strIngredient4": "Salt",
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "1 1/2 oz ",
  "strMeasure2": "1/2 oz ",
  "strMeasure3": "1 oz ",
  "strMeasure4": null,
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": "https://commons.wikimedia.org/wiki/File:Klassiche_Margarita.jpg",
  "strImageAttribution": "Cocktailmarler",
  "strCreativeCommonsConfirmed": "Yes",
  "dateModified": "2015-08-18 14:42:59"
  }
  ]
  };

export const id52773 = {
  "meals": [
  {
  "idMeal": "52773",
  "strMeal": "Honey Teriyaki Salmon",
  "strDrinkAlternate": null,
  "strCategory": "Seafood",
  "strArea": "Japanese",
  "strInstructions": "Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
  "strTags": "Fish,Breakfast,DateNight",
  "strYoutube": "https://www.youtube.com/watch?v=4MpYuaJsvRw",
  "strIngredient1": "Salmon",
  "strIngredient2": "Olive oil",
  "strIngredient3": "Soy Sauce",
  "strIngredient4": "Sake",
  "strIngredient5": "Sesame Seed",
  "strIngredient6": "",
  "strIngredient7": "",
  "strIngredient8": "",
  "strIngredient9": "",
  "strIngredient10": "",
  "strIngredient11": "",
  "strIngredient12": "",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": null,
  "strIngredient17": null,
  "strIngredient18": null,
  "strIngredient19": null,
  "strIngredient20": null,
  "strMeasure1": "1 lb",
  "strMeasure2": "1 tablespoon",
  "strMeasure3": "2 tablespoons",
  "strMeasure4": "2 tablespoons",
  "strMeasure5": "4 tablespoons",
  "strMeasure6": "",
  "strMeasure7": "",
  "strMeasure8": "",
  "strMeasure9": "",
  "strMeasure10": "",
  "strMeasure11": "",
  "strMeasure12": "",
  "strMeasure13": "",
  "strMeasure14": "",
  "strMeasure15": "",
  "strMeasure16": null,
  "strMeasure17": null,
  "strMeasure18": null,
  "strMeasure19": null,
  "strMeasure20": null,
  "strSource": null,
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
  }
  ]
  }

export const id178319 = {
  "drinks": [
  {
  "idDrink": "178319",
  "strDrink": "Aquamarine",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Cocktail",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Martini Glass",
  "strInstructions": "Shake well in a shaker with ice.\r\nStrain in a martini glass.",
  "strInstructionsES": "Agite bien en una coctelera con hielo. Cuela en una copa de Martini.",
  "strInstructionsDE": null,
  "strInstructionsFR": null,
  "strInstructionsIT": "Shakerare bene in uno shaker con ghiaccio.\r\nFiltrare in una coppetta Martini.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg",
  "strIngredient1": "Hpnotiq",
  "strIngredient2": "Pineapple Juice",
  "strIngredient3": "Banana Liqueur",
  "strIngredient4": null,
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "2 oz",
  "strMeasure2": "1 oz",
  "strMeasure3": "1 oz",
  "strMeasure4": "",
  "strMeasure5": "",
  "strMeasure6": "",
  "strMeasure7": "",
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": null
  }
  ]
  }

export const id178320 = {
"drinks": [
{
"idDrink": "178320",
"strDrink": "Banana Cream Pi",
"strDrinkAlternate": null,
"strTags": null,
"strVideo": null,
"strCategory": "Cocktail",
"strIBA": null,
"strAlcoholic": "Alcoholic",
"strGlass": "Wine Glass",
"strInstructions": "Serve over ice.",
"strInstructionsES": null,
"strInstructionsDE": null,
"strInstructionsFR": null,
"strInstructionsIT": "Servire con ghiaccio",
"strInstructionsZH-HANS": null,
"strInstructionsZH-HANT": null,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/m5p67n1582474609.jpg",
"strIngredient1": "Malibu Rum",
"strIngredient2": "Banana Liqueur",
"strIngredient3": "Pineapple Juice",
"strIngredient4": null,
"strIngredient5": null,
"strIngredient6": null,
"strIngredient7": null,
"strIngredient8": null,
"strIngredient9": null,
"strIngredient10": null,
"strIngredient11": null,
"strIngredient12": null,
"strIngredient13": null,
"strIngredient14": null,
"strIngredient15": null,
"strMeasure1": "1 oz",
"strMeasure2": "1 oz",
"strMeasure3": "Top",
"strMeasure4": "",
"strMeasure5": "",
"strMeasure6": "",
"strMeasure7": "",
"strMeasure8": null,
"strMeasure9": null,
"strMeasure10": null,
"strMeasure11": null,
"strMeasure12": null,
"strMeasure13": null,
"strMeasure14": null,
"strMeasure15": null,
"strImageSource": null,
"strImageAttribution": null,
"strCreativeCommonsConfirmed": "Yes",
"dateModified": null
}
]
}
